---
version: '3'
services:

  daemon:
    build: .
    environment:
      IMAP_URL: ${IMAP_URL}
      WEBHOOK_URL: http://mock:5000/
      ON_SUCCESSS: 'delete'
    volumes:
      - .:/usr/src/app
    networks:
      - imap-to-webhook-network

  mock:
    build:
      context: mock
    ports:
      - 5000:5000
    networks:
      - imap-to-webhook-network

networks:
  imap-to-webhook-network:
    driver: bridge
